name: Basic Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Test basic functionality
      run: |
        echo "🚀 Starting basic test..."
        echo "Current directory: $(pwd)"
        echo "Files in directory:"
        ls -la
        echo "✅ Basic test completed successfully!"
